# Site settings
title: zvdifo | blog
email: zvdifo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  © 2015 zvdifo. Powered by Jekyll
baseurl: "" # the subpath of your site, e.g. /blog/
url: "localhost:4000" # the base hostname & protocol for your site
github_username:  zvdifo
linkedin_username:  shan yu
linkedin_ID:  https://cn.linkedin.com/pub/shan-yu/77/104/a91
douban_username: zvdifo
douban_ID: people/56090737


# Build settings
markdown: kramdown
paginate: 5